FROM maven:3.9.9-eclipse-temurin-22-alpine AS build

WORKDIR /app

COPY pom.xml .
COPY shared-domain ./shared-domain
COPY scheduling-service ./scheduling-service
COPY notification-service ./notification-service

RUN mvn clean package -DskipTests

FROM eclipse-temurin:22-jre

WORKDIR /app

COPY --from=build /app/scheduling-service/target/scheduling-service-1.0.0.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
